dist: xenial
sudo: required

matrix:
  include:
    - os : osx
      osx_image: xcode12
    - os : osx
      osx_image: xcode11.3
    - os : osx
      osx_image: xcode10.1
    - os: linux
      sudo: required

services:
  - docker
  - xvfb

branches:
  only:
    - master
    - devel

notifications:
  email:
    recipients:
      - dilawar.s.rajput@gmail.com
    on_success: change
    on_failure: always

script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then (cd devel && ./build_wheels_osx.sh); fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then (cd devel && make) ; fi

