name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6,3.7,3.8]

    steps:
    - uses: actions/checkout@v2
    - name: "Setup Python ${{ matrix.python-version }}"
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: install
      run: |
        sudo apt -y update
        sudo apt -y install cmake libjpeg-dev libtiff-dev freeglut3-dev libxi-dev libxmu-dev
        sudo apt -y install xvfb
        # Remove linuxbrew
        sudo ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall)" || echo "Failed to remove linuxbrew"
    - name: configure
      run: | 
        cmake --version
        which python
        python -c "import sys; print(sys.version)"
        python -m pip install pytest matplotlib numpy wheel
        mkdir build && cd build && cmake -DOPTION_PYTHON=ON -DOPTION_EXAMPLES=ON ..
    - name: make
      run: cd build && make -j2 && make wheel
    - name: ctest -j2
      run: |
        # From https://github.com/processing/processing/wiki/Running-without-a-Display
        sudo Xvfb :1 -screen 0 1024x768x24 </dev/null &
        export DISPLAY=":1"
        cd build && ctest --output-on-failure && make pyexamples 
