name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build manylinux2010 wheels
      run: docker build . --file scripts/Dockerfile --tag smoldyn-manylinux:$(date +%s)
