name: Linux Wheels
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
      
jobs:
  container:
    runs-on: ubuntu-latest
    container: quay.io/pypa/manylinux2010_x86_64
    env:
        SMOLDYN_PYPI_TOKEN: ${{ secrets.SMOLDYN_PYPI_TOKEN }}
    steps:
      - run: |
          yum -y update
          yum -y install freeglut-devel libtiff-devel libXmu-devel libXi-devel tree && yum clean all
          cd ~ && tree
          git clone $GITHUB_SERVER/$GITHUB_REPOSITORY -b $GITHUB_REF --depth 10
          # git clone https://github.com/ssandrews/Smoldyn -b master --depth 10
          cd Smoldyn/scripts && PYPI_PASSWORD=$SMOLDYN_PYPI_TOKEN ./build_wheels_linux.sh 
        name: Building wheel in ManuLinux container

