name: Linux Wheels
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
      
jobs:
  vm:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Do nothing here"
        name: Dummy job
  container:
    runs-on: ubuntu-latest
    container: quay.io/pypa/manylinux2010_x86_64
    env:
        SMOLDYN_PYPI_TOKEN: ${{ secrets.SMOLDYN_PYPI_TOKEN }}
    steps:
      - run: |
          yum -y update
          yum -y install freeglut-devel libtiff-devel libXmu-devel libXi-devel tree && yum clean all
          cd / && tree 
          cd ~
          /opt/python/cp38-cp38/bin/python -m pip install cmake 
          ln -s /opt/python/cp38-cp38/bin/cmake /usr/local/bin/cmake
          git clone https://github.com/dilawar/Smoldyn -b master --depth 10
          cd Smoldyn/scripts && PYPI_PASSWORD=$SMOLDYN_PYPI_TOKEN ./build_wheels_linux.sh 
        name: Building wheel in ManuLinux container

