name: Wheels

on:
  push:
    branches:
      - master
    tags:
      - 'v**'
  pull_request:
    branches: 
      - master
      
jobs:
  wheel:
    runs-on: ubuntu-latest
    env:
        SMOLDYN_PYPI_TOKEN: ${{ secrets.SMOLDYN_PYPI_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Building wheel in ManuLinux container
        run: |
          ls -ltR
          export PYPI_PASSWORD=$SMOLDYN_PYPI_TOKEN
          cd scripts && make wheels

      # BioSimulators
      - name: Build BioSimulators Docker image
        if: startsWith(github.ref, 'refs/tags/v')
        env:
          TAG: ${{ github.ref }}
        run: |
          cp /root/wheelhouse/smoldyn-*-cp39-*.whl scripts/
          cd scripts
          VERSION="${TAG/refs\/tags\/v/}"
          REVISION=$(git rev-parse HEAD)
          CREATED=$(date --rfc-3339=seconds | sed 's/ /T/')
          docker build \
            --file Dockerfile-BioSimulators \
            --tag ghcr.io/ssandrews/smoldyn/biosimulators_smoldyn:${VERSION} \
            --tag ghcr.io/ssandrews/smoldyn/biosimulators_smoldyn:latest \
            --build-arg VERSION=${VERSION} \
            --label org.opencontainers.image.revision=${REVISION} \
            --label org.opencontainers.image.created=${CREATED} \
            .

      - name: Push BioSimulators Docker image
        if: startsWith(github.ref, 'refs/tags/v') && false
        env:
          TAG: ${{ github.ref }}
        run: |
          VERSION="${TAG/refs\/tags\/v/}"
          docker login ghcr.io \
            --username ${{ secrets.BIOSIMULATORS_GH_USERNAME }} \
            --password ${{ secrets.BIOSIMULATORS_GH_TOKEN }}
          docker push ghcr.io/ssandrews/smoldyn/biosimulators_smoldyn:${VERSION}
          docker push ghcr.io/ssandrews/smoldyn/biosimulators_smoldyn:latest

      - name: Submit Smoldyn to BioSimulators
        if: startsWith(github.ref, 'refs/tags/v') && false
        env:
          TAG: ${{ github.ref }}
        run: |
          VERSION="${TAG/refs\/tags\/v/}"
          REVISION=$(git rev-parse HEAD)
          curl \
            -X POST \
            -u ${{ secrets.BIOSIMULATORS_GH_USERNAME }}:${{ secrets.BIOSIMULATORS_GH_TOKEN }} \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/biosimulators/Biosimulators/issues \
            -d "{\"labels\": [\"Validate/submit simulator\"], \"title\": \"Submit Smoldyn ${VERSION}\", \"body\": \"---\nid: smoldyn\nversion: ${VERSION}\nspecificationsUrl: https://raw.githubusercontent.com/ssandrews/Smoldyn/${REVISION}/biosimulators.json\nspecificationsPatch:\n  version: ${VERSION}\n  image:\n    url: ghcr.io/ssandrews/smoldyn/biosimulators_smoldyn:${VERSION}:${VERSION}\nvalidateImage: true\ncommitSimulator: true\n\n---\"}"
